### ISSUE TITLE
Ignored files should still be processed for dependencies

### ISSUE THREAD

**Issue by asabil** [smysnk/gulp-rev-all#19]
This is useful when ignoring  index.html for example where you want to substitute references to the various assets but don't want the file itself to be versioned.

**Comment by farism** [comment]
Hey @smysnk how do you feel about second option to ignore a pattern for processing? e.g. I'm generating a separate sourcemap files, I want to be able to rev these files and have them update their reference in the corresponding bundled files, but I don't want to process/update the dependencies in the sourcemaps themselves because this is really slow. I just find the current way of only ignoring binary files to be rather limiting.

I was thinking something like ignoreDeps: ['*.map']
